name: MPRI PRFA CI

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:

  build:

    runs-on: ubuntu-latest

    env:
      fail-fast: true

    steps:

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Docker-Coq-Action
        uses: coq-community/docker-coq-action@v1
        with:
          custom_image: 'yforster/coq:8.19.1--clang-11--compcert-3.13.1--extlib-0.12.1--equations-1.3--metacoq-1.3.1'
          before_install: |
            startGroup "Print opam config"
              sudo chown -R coq:coq .
              opam config list; opam repo list; opam list
            endGroup
          before_script: |
            startGroup "Workaround permission issue"
              sudo chown -R coq:coq .  # <--
              opam exec -- ocamlfind list
            endGroup
          install: |
            startGroup "Overwrite default install script"
            endGroup
          script: |
            startGroup "Build project"
              opam exec -- make -j 2
              opam exec -- make coqdoc
            endGroup
          uninstall: |
            startGroup "Clean project"
            endGroup

      - name: Revert permissions
        # to avoid a warning at cleanup time
        if: ${{ always() }}
        run: sudo chown -R 1001:116 .  # <--

      - name: Build homepage
        uses: docker://pandoc/core:2.9
        with:
          args: >-  # allows you to break string into multiple lines
            --standalone
            --output=doc/index.html
            --css=github-pandoc.css
            --metadata title="Proof assistants"
            README.md

      - name: Move images
        run: mv img doc

      - name: Setup Pages
        if: github.ref_name == github.event.repository.default_branch
        uses: actions/configure-pages@v3
      - name: Upload artifact
        if: github.ref_name == github.event.repository.default_branch
        uses: actions/upload-pages-artifact@v1
        with:
          path: 'doc'
      - name: Deploy to GitHub Pages
        if: github.ref_name == github.event.repository.default_branch
        id: deployment
        uses: actions/deploy-pages@v1
